    - name: Ensure the user directory exists
      file:
        path: /home/{{ user_name }}/monitoring
        state: directory
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0755'

    - name: Create Docker network 'monitoring' (ignore if already exists)
      command: docker network create monitoring
      ignore_errors: yes
      
    - name: Create docker-compose.yml for Node Exporter
      copy:
        content: |
          services:
            node-exporter:
                image: prom/node-exporter:latest
                container_name: node-exporter
                restart: unless-stopped
                volumes:
                    - /proc:/host/proc:ro
                    - /sys:/host/sys:ro
                    - /:/rootfs:ro
                command:
                    - '--path.procfs=/host/proc'
                    - '--path.rootfs=/rootfs'
                    - '--path.sysfs=/host/sys'
                    - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
                ports:
                    - "9100:9100"
                networks:
                    - monitoring
          networks:
            monitoring:
              external: true
              

        dest: /home/{{ user_name }}/monitoring/docker-compose.yml
        owner: "{{ user_name }}"
        group: "{{ user_name }}"
        mode: '0644'

    - name: Run Docker Compose to start Node Exporter
      shell: docker compose down && docker compose up -d
      args:
        chdir: /home/{{ user_name }}/monitoring
