--- 
# tasks file for roles/prometheus

- name: Create a test folder
  file:
    path: "/home/{{ user_name }}/test_folder"
    state: directory
    mode: '0755'

- name: Create a directory if it does not exist
  file:
    path: /home/{{ user_name }}/monitoring/prometheus
    state: directory
    mode: '0755'

- name: Create prometheus.yml for Prometheus
  copy:
    content: |
      global:
        scrape_interval: 30s

      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']

        - job_name: 'node'
          static_configs:
            - targets: ["{{ node_domain4 }}"]

        - job_name: 'all-server'
          static_configs:
            - targets:
              - "{{ node_domain1 }}"
              - "{{ node_domain2 }}"
              - "{{ node_domain3 }}"
              - "{{ node_domain4 }}"

        - job_name: 'aws'
          static_configs:
            - targets:
              - "{{ node_domain1 }}"
              - "{{ node_domain2 }}"

        - job_name: 'biznet'
          static_configs:
            - targets:
              - "{{ node_domain3 }}"
              - "{{ node_domain4 }}"

        - job_name: 'cadvisor'
          scrape_interval: 15s
          static_configs:
            - targets:
              - "{{ server1 }}":"{{ cadvisor_port }}"
              - "{{ server2 }}":"{{ cadvisor_port }}"
              - "{{ server3 }}":"{{ cadvisor_port }}"
              - "{{ monitoring_server }}":"{{ cadvisor_port }}"


    dest: /home/{{ user_name }}/monitoring/prometheus/prometheus.yml
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'

- name: Create Docker network 'monitoring' (ignore if already exists)
  command: docker network create monitoring
  ignore_errors: yes

- name: Create docker-compose.yml for Prometheus
  copy:
    content: |
      services:
        prometheus:
          image: prom/prometheus:latest
          container_name: prometheus
          user: "${UID}:${GID}"
          restart: unless-stopped
          volumes:
          - ./prometheus.yml:/etc/prometheus/prometheus.yml
          - ./prometheus_data:/prometheus
          command: 
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
            - --web.console.libraries=/etc/prometheus/console_libraries
            - --web.console.templates=/etc/prometheus/consoles
            - --web.enable-lifecycle
          ports:
            - "9090:9090"
          networks:
            - monitoring

      networks:
        monitoring:
          external: true

      volumes:
        prometheus_data: {}

    dest: /home/{{ user_name }}/monitoring/prometheus/docker-compose.yml
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
    mode: '0644'


- name: Remove existing Prometheus container if it exists
  command: docker rm -f prometheus
  ignore_errors: yes

- name: Run Docker Compose to start Prometheus
  shell: docker compose down prometheus && docker compose up -d
  args:
    chdir: /home/{{ user_name }}/monitoring/prometheus