---
# tasks file for roles/nginx

- name: Update apt cache
  apt:
    update_cache: yes

- name: Pull nginx image
  docker_image:
    name: nginx:alpine
    source: pull

- name: Deploy nginx on top Docker
  docker_container:
    name: nginx
    image: nginx:alpine
    state: started
    published_ports:
      - "80:80"  
    restart_policy: always  

